title: Happy Birthday Mr. Zhou
author: UU
description: >-
  Congratulations on being one step closer to success!  The coming year is brimming with challenges that propel you forward, achievements that raise you higher, and a wealth of new directions and motivations. May you navigate this journey with strength and wisdom, and may I have the honor of accompanying you along the way.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
